name: Gatling Performance Tests

on:
  push:
  workflow_dispatch:

jobs:
  gatling_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Run Gatling Tests for desired simulation
        run: |
          mvn gatling:test -Dgatling.simulationClass=tests.HealthSimulations -P smoke

      - name: Upload Gatling Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gatling-report
          path: target/gatling
