name: Gatling Performance Tests

on:
  push:
  workflow_dispatch:

jobs:
  gatling_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Run Gatling Simulations Sequentially
        run: |
          simulations=(
            HealthSimulations
            CreateUserSimulations
            GetUserSimulations
            UpdateUserSimulations
            UpdateUserPasswordSimulations
            LogoutUserSimulations
            CreateNoteSimulations
            GetNoteSimulations
            UpdateNoteSimulations
            UpdateNoteStatusSimulations
            GetAllNotesSimulations
            DeleteNoteSimulations
          )

          for sim in "${simulations[@]}"
          do
            echo "=== Running simulation: $sim ==="
            mvn gatling:test -Dgatling.simulationClass=tests.$sim -P smoke
            echo "=== Sleeping 60s before next simulation ==="
            sleep 60
          done

      - name: Upload Gatling Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gatling-reports
          path: target/gatling
